name: verilator-test
on:
  push:
    branches-ignore:
      - '*'
jobs:
  ubuntu-20-functional-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt install -y verilator gtkwave build-essential libz-dev
      - name: Run NSCSCC functional tests
        run: make vsim -j VSIM_OPT=1 VSIM_ARGS='--no-status'

  ubuntu-20-performance-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt install -y verilator gtkwave build-essential libz-dev
      - name: Run NSCSCC performance tests
        run: make vsim -j VSIM_OPT=1 TEST=coremark VSIM_ARGS='--no-status'

  ubuntu-20-cache-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt install -y verilator gtkwave build-essential libz-dev
      - name: Run cache tests
        run: make vsim -j VSIM_OPT=1 TARGET=refcpu/VCacheTop VSIM_ARGS='--no-status'

  ubuntu-18-functional-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt install -y gtkwave make clang-10 libc++-10-dev libc++abi-10-dev libz-dev
          wget -O verilator4.deb https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb
          sudo dpkg -i verilator4.deb
          sudo ln -s /usr/local/share/verilator /usr/share/
      - name: Run NSCSCC functional tests
        run: make vsim -j USE_CLANG=1 VSIM_OPT=1 VSIM_ARGS='--no-status'

  ubuntu-18-performance-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt install -y gtkwave make clang-10 libc++-10-dev libc++abi-10-dev libz-dev
          wget -O verilator4.deb https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb
          sudo dpkg -i verilator4.deb
          sudo ln -s /usr/local/share/verilator /usr/share/
      - name: Run NSCSCC performance tests
        run: make vsim -j USE_CLANG=1 VSIM_OPT=1 TEST=coremark VSIM_ARGS='--no-status'

  ubuntu-18-cache-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt install -y gtkwave make clang-10 libc++-10-dev libc++abi-10-dev libz-dev
          wget -O verilator4.deb https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb
          sudo dpkg -i verilator4.deb
          sudo ln -s /usr/local/share/verilator /usr/share/
      - name: Run cache tests
        run: make vsim -j USE_CLANG=1 VSIM_OPT=1 TARGET=refcpu/VCacheTop VSIM_ARGS='--no-status'